/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   multipart-payload-transformer.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

import {PolymerElement} from '@polymer/polymer/polymer-element.js';

export {MultipartPayloadTransformer};

declare namespace ApiElements {

  /**
   * An element that contains methods to transform FormData object
   * into Multipart message and ArrayBuffer
   *
   * ## Example
   *
   * ```html
   * <multipart-payload-transformer form-data="[[formData]]"></multipart-payload-transformer>
   * ```
   *
   * ## Legacy dependencies
   *
   * If targeting legacy browsers add polyfill for Fetch API.
   */
  class MultipartPayloadTransformer extends PolymerElement {

    /**
     * A form data object to transform.
     */
    formData: FormData|null;

    /**
     * Latest generated boundary value for the multipart forms.
     * Each call to `generateMessage()` or `generatePreview()` will
     * generate new content type and therefore boundary value.
     */
    boundary: string|null|undefined;

    /**
     * Latest generated content-type value for the multipart forms.
     * Each call to `generateMessage()` or `generatePreview()` will
     * generate new content type value.
     */
    contentType: string|null|undefined;

    /**
     * Generates an ArrayBuffer instance from the FormData object.
     *
     * @returns A resolved promise when produces ArrayBuffer.
     */
    generateMessage(): Promise<String|null>;

    /**
     * Informs other ARC elements about content type change.
     * If boundary is added to the content type string then it is reported in
     * a separate event.
     *
     * @param contentType New cintent type.
     */
    _processContentType(contentType: String|null): void;

    /**
     * Generates a preview of the multipart messgae.
     *
     * @returns A promise resolved to a string message.
     */
    generatePreview(): Promise<String|null>;

    /**
     * Convert ArrayBuffer to readable form
     *
     * @returns Converted string
     */
    arrayBufferToString(buffer: ArrayBuffer|null): String|null;
  }
}

declare global {

  interface HTMLElementTagNameMap {
    "multipart-payload-transformer": ApiElements.MultipartPayloadTransformer;
  }
}
